"""initial schema

Revision ID: 00acc2d1b0d0
Revises: 
Create Date: 2026-08-20 18:22:35.469054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00acc2d1b0d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('certifications', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructors_email'), 'instructors', ['email'], unique=True)
    op.create_index(op.f('ix_instructors_id'), 'instructors', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initials', sa.String(), nullable=False),
    sa.Column('avatar_variant', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('next_session', sa.String(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('sessions_total', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('amount_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('session_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('pay_rate', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_listings_id'), 'session_listings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_listings_id'), table_name='session_listings')
    op.drop_table('session_listings')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_instructors_id'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_email'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
