"""add lesson request lessons_per_week

Revision ID: 0c48e670ce65
Revises: a40d49d2c976
Create Date: 2026-08-23 19:40:07.552333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c48e670ce65'
down_revision: Union[str, Sequence[str], None] = 'a40d49d2c976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.suspended / instructors.suspended / lesson_requests.paid
    # to nullable=True here — same recurring SQLite NOT NULL reflection
    # quirk as every prior migration in this repo, not real drift.
    # Deliberately dropped.
    op.add_column('lesson_requests', sa.Column('lessons_per_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_requests', 'lessons_per_week')
    # ### end Alembic commands ###
