"""add instructor geocoded city fields

Revision ID: 107f32b99500
Revises: 7811cf2dbe3c
Create Date: 2026-08-23 22:14:54.777687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107f32b99500'
down_revision: Union[str, Sequence[str], None] = '7811cf2dbe3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.suspended / instructors.suspended / lesson_requests.paid
    # to nullable=True here — same recurring SQLite NOT NULL reflection
    # quirk as every prior migration in this repo, not real drift.
    # Deliberately dropped.
    op.add_column('instructors', sa.Column('city_name', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('state_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'state_name')
    op.drop_column('instructors', 'city_name')
    # ### end Alembic commands ###
