"""add instructor stripe connect fields

Revision ID: 368da3e433e8
Revises: e45f61668035
Create Date: 2026-08-26 14:28:52.538571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368da3e433e8'
down_revision: Union[str, Sequence[str], None] = 'e45f61668035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.email_notifications / customers.suspended /
    # instructors.email_notifications / instructors.suspended /
    # lesson_requests.paid to nullable=True here — same recurring SQLite
    # NOT NULL reflection quirk as every prior migration in this repo,
    # not real drift. Deliberately dropped. stripe_transfers_enabled
    # gets server_default=sa.false() (not just the model's Python-level
    # default=False) for the same reason established in b19292ab080d —
    # existing instructor rows need a real False, not NULL, since NULL
    # would still evaluate falsy but inconsistently across DBs.
    op.add_column('instructors', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('instructors', sa.Column('stripe_transfers_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'stripe_transfers_enabled')
    op.drop_column('instructors', 'stripe_account_id')
    # ### end Alembic commands ###
