"""add customer geocoded address fields

Revision ID: 7811cf2dbe3c
Revises: 0c48e670ce65
Create Date: 2026-08-23 21:20:22.848303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7811cf2dbe3c'
down_revision: Union[str, Sequence[str], None] = '0c48e670ce65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.suspended / instructors.suspended / lesson_requests.paid
    # to nullable=True here — same recurring SQLite NOT NULL reflection
    # quirk as every prior migration in this repo, not real drift.
    # Deliberately dropped.
    op.add_column('customers', sa.Column('address_line', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('city_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('state_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'state_name')
    op.drop_column('customers', 'city_name')
    op.drop_column('customers', 'address_line')
    # ### end Alembic commands ###
