"""make instructor and customer passwords nullable for google sign-in

Revision ID: 8210bb33d350
Revises: 107f32b99500
Create Date: 2026-08-24 10:08:35.661125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8210bb33d350'
down_revision: Union[str, Sequence[str], None] = '107f32b99500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.suspended / instructors.suspended / lesson_requests.paid
    # to nullable=True here — same recurring SQLite NOT NULL reflection
    # quirk as every prior migration in this repo, not real drift.
    # Deliberately dropped. The two hashed_password changes below ARE
    # real: a Google-only account has no password at all.
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
