"""add scheduling and location

Revision ID: 8db11c1fa3fb
Revises: 12d63c521f50
Create Date: 2026-08-20 12:54:12.055592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db11c1fa3fb'
down_revision: Union[str, Sequence[str], None] = '12d63c521f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_blocks_id'), 'availability_blocks', ['id'], unique=False)
    op.create_table('lesson_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('requested_day', sa.Integer(), nullable=False),
    sa.Column('requested_start_time', sa.String(), nullable=False),
    sa.Column('requested_end_time', sa.String(), nullable=False),
    sa.Column('matched_start_time', sa.String(), nullable=True),
    sa.Column('matched_end_time', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_requests_id'), 'lesson_requests', ['id'], unique=False)
    op.add_column('customers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('instructors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('instructors', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'longitude')
    op.drop_column('instructors', 'latitude')
    op.drop_column('customers', 'longitude')
    op.drop_column('customers', 'latitude')
    op.drop_index(op.f('ix_lesson_requests_id'), table_name='lesson_requests')
    op.drop_table('lesson_requests')
    op.drop_index(op.f('ix_availability_blocks_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    # ### end Alembic commands ###
