"""add multi-window lesson request availability and package sessions

Revision ID: a40d49d2c976
Revises: 015a253d8bb8
Create Date: 2026-08-23 16:35:02.726977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40d49d2c976'
down_revision: Union[str, Sequence[str], None] = '015a253d8bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_request_availability_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_request_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_request_id'], ['lesson_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_request_availability_windows_id'), 'lesson_request_availability_windows', ['id'], unique=False)
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.suspended / instructors.suspended / lesson_requests.paid
    # to nullable=True here — same recurring SQLite NOT NULL reflection
    # quirk as every prior migration in this repo, not real drift.
    # Deliberately dropped. requested_day/start/end below IS a real,
    # intentional change (see models.LessonRequest's docstring).
    # SQLite doesn't support ALTER COLUMN ... DROP NOT NULL or adding a
    # foreign key to an existing table directly — batch mode recreates
    # the table under the hood, same as migrations 61908be0a3e1 and
    # eec36154bc48 already do for the same reason.
    with op.batch_alter_table('lesson_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sessions_total', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('session_number', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('package_request_id', sa.Integer(), nullable=True))
        batch_op.alter_column('requested_day', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('requested_start_time', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('requested_end_time', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.create_foreign_key('fk_lesson_requests_package_request_id', 'lesson_requests', ['package_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    NOTE: this will fail with a NOT NULL violation on requested_day if
    any pending (not yet matched) multi-window LessonRequest row exists
    at downgrade time, since those legitimately have no single window
    yet — same accepted risk-tolerance as this project's other
    documented one-way-in-practice migrations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lesson_requests_package_request_id', type_='foreignkey')
        batch_op.alter_column('requested_end_time', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('requested_start_time', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('requested_day', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('package_request_id')
        batch_op.drop_column('session_number')
        batch_op.drop_column('sessions_total')
        batch_op.drop_column('package')
    op.drop_index(op.f('ix_lesson_request_availability_windows_id'), table_name='lesson_request_availability_windows')
    op.drop_table('lesson_request_availability_windows')
    # ### end Alembic commands ###
