"""add client details fields and session listing filter/sort fields

Revision ID: b623b8113c95
Revises: cd44acd0a348
Create Date: 2026-08-20 20:39:00.563341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b623b8113c95'
down_revision: Union[str, Sequence[str], None] = 'cd44acd0a348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_lessons_id'), 'client_lessons', ['id'], unique=False)
    # NOTE: autogenerate also proposed loosening bookings.paid/lesson_requests.paid
    # back to nullable=True here — that's SQLite's imperfect NOT NULL reflection
    # after an ADD COLUMN, not a real schema drift. Deliberately dropped; see
    # migration cd44acd0a348 for why those columns are nullable=False on purpose.
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('location_type', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('lessons_per_week', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('available_days', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('weekday_start', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('weekday_end', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('weekend_start', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('weekend_end', sa.String(), nullable=True))
    op.add_column('session_listings', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('session_listings', sa.Column('lessons_per_week', sa.Integer(), nullable=True))
    op.add_column('session_listings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('session_listings', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('session_listings', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_listings', 'created_at')
    op.drop_column('session_listings', 'longitude')
    op.drop_column('session_listings', 'latitude')
    op.drop_column('session_listings', 'lessons_per_week')
    op.drop_column('session_listings', 'day_of_week')
    op.drop_column('clients', 'weekend_end')
    op.drop_column('clients', 'weekend_start')
    op.drop_column('clients', 'weekday_end')
    op.drop_column('clients', 'weekday_start')
    op.drop_column('clients', 'available_days')
    op.drop_column('clients', 'lessons_per_week')
    op.drop_column('clients', 'start_date')
    op.drop_column('clients', 'location_type')
    op.drop_column('clients', 'address')
    op.drop_index(op.f('ix_client_lessons_id'), table_name='client_lessons')
    op.drop_table('client_lessons')
    # ### end Alembic commands ###
