"""add distance preference, pending broadcast, deferred payment, notes

Revision ID: cd44acd0a348
Revises: 8db11c1fa3fb
Create Date: 2026-08-20 19:13:39.956780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd44acd0a348'
down_revision: Union[str, Sequence[str], None] = '8db11c1fa3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('paid', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('instructors', sa.Column('max_travel_distance_km', sa.Float(), nullable=True))
    op.add_column('lesson_requests', sa.Column('paid', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('lesson_requests', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_requests', 'notes')
    op.drop_column('lesson_requests', 'paid')
    op.drop_column('instructors', 'max_travel_distance_km')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'paid')
    # ### end Alembic commands ###
