"""add phone contact info and reviews

Revision ID: d6381830b851
Revises: b623b8113c95
Create Date: 2026-08-21 00:45:45.255802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6381830b851'
down_revision: Union[str, Sequence[str], None] = 'b623b8113c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('lesson_request_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['lesson_request_id'], ['lesson_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'booking_id', name='uq_review_customer_booking'),
    sa.UniqueConstraint('customer_id', 'lesson_request_id', name='uq_review_customer_lesson_request')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # NOTE: autogenerate also proposed loosening bookings.paid/lesson_requests.paid
    # back to nullable=True here — same SQLite NOT NULL reflection quirk as
    # migration b623b8113c95, not real drift. Deliberately dropped.
    op.add_column('clients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('phone', sa.String(), server_default='', nullable=False))
    op.add_column('instructors', sa.Column('phone', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'phone')
    op.drop_column('customers', 'phone')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'email')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
