"""add specialty verification requests

Revision ID: e45f61668035
Revises: e7fdb2cdc7a6
Create Date: 2026-08-26 13:48:06.173128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45f61668035'
down_revision: Union[str, Sequence[str], None] = 'e7fdb2cdc7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.email_notifications / customers.suspended /
    # instructors.email_notifications / instructors.suspended /
    # lesson_requests.paid to nullable=True here — same recurring SQLite
    # NOT NULL reflection quirk as every prior migration in this repo, not
    # real drift. Deliberately dropped.
    op.create_table('specialty_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('certification_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialty_verifications_id'), 'specialty_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialty_verifications_id'), table_name='specialty_verifications')
    op.drop_table('specialty_verifications')
    # ### end Alembic commands ###
