"""add customer email_notifications and profile fields

Revision ID: e7fdb2cdc7a6
Revises: b19292ab080d
Create Date: 2026-08-24 15:07:49.859264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fdb2cdc7a6'
down_revision: Union[str, Sequence[str], None] = 'b19292ab080d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed loosening bookings.paid /
    # customers.suspended / instructors.email_notifications /
    # instructors.suspended / lesson_requests.paid to nullable=True here —
    # same recurring SQLite reflection quirk as every prior migration in
    # this repo (see b19292ab080d), not real drift. Deliberately dropped.
    # server_default=sa.true() (not just the model's Python-level
    # default=True) is required so existing customer rows get real
    # notifications-on, not NULL — see b19292ab080d for the full reasoning
    # (a NULL would evaluate falsy in every `if customer.email_notifications:`
    # guard, silently turning notifications off for everyone already using
    # the app).
    op.add_column('customers', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'email_notifications')
    # ### end Alembic commands ###
